site_name: Beachfront
markdown_extensions:
- sane_lists
- smarty
- toc:
    permalink: True
    separator: _
pages:
- Home: index.md
- User Guide:
  - Beachfront: userguide/index.md
  - Algorithms: userguide/algorithms.md
  - Tide Prediction: userguide/tide-prediction.md
