site_name: Beachfront Documentation
markdown_extensions:
  - sane_lists
  - smarty
  - toc:
      permalink: True
      separator: _
pages:
  - Home: index.md
  - User Guide:
      userguide/index.md
